Fix re-allocation of getpw_r buffer
gifnksm/etc-passwd pull request #6
Opened 2024-07-07 13:17 UTC by mbuesch

The use of `Vec::reserve` is not correct. It does not actually reallocate the buffer in this case. See the documentation of `Vec::reserve`
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve

```
After calling reserve, capacity will be greater than or equal to self.len() + additional.
```

But `self.len()` is always zero, because it is only ever attempted to set the capacity not the len.

This problem will result in an infinite loop in case of required reallocation.

Fix this by actually resizing and therefore increasing `self.len()`. This has the downside of requireing initialization of the buffer content. But I think it is a good idea to initialize the buffer before passing it to the C function. We also do that for `struct passwd` already.

2024-07-08 11:55 UTC, gifnksm requested changes
Thanks for making the pull request.

I don't think it is wrong to use `Vec::reserve()` here.
`buf.len()` is always zero, but `amt` doubles each time it goes around the loop.
Thus, the allocated size should also increase.

But as you point out, initializing the buffer before passing it to the C function is a good idea.
So I would like to merge this change, but I have one comment.
Could you please make the change.

2024-07-08 11:55 UTC, gifnksm commented on src/lib.rs
>      let mut buf = Vec::with_capacity(amt);
Could you replace this line with the following code.


```rust
let mut buf = vec![0; amt];
```

The reason is that the intent of the code is more readable, and the compiler optimizations may translate it into a more efficient allocation function call (Rust's allocator interface has `GlobalAlloc::alloc_zeroed()`).

2024-07-08 15:08 UTC, mbuesch commented
Yes, you are right. I was completely confused by the terms.
I will make the requested changes and adjust the commit message to match.
Thanks for your review!

2024-07-08 15:20 UTC, mbuesch commented
updated.

2024-07-09 09:57 UTC, merged

2024-07-09 09:57 UTC, gifnksm commented
Thank you!